---

- name: Hadoop - create package dir
  file:
    path: /home/ubuntu/packages
    mode: 0755
    owner: ubuntu
    group: ubuntu

- name: PyCharm - download 2017.2.4
  get_url:
    url: "https://download.jetbrains.com/python/pycharm-community-2017.2.4.tar.gz"
    dest: /home/ubuntu/packages
    mode: 0444
    owner: ubuntu
    group: ubuntu
    validate_certs: false

- name: PyCharm - unpack 2017.2.4
  unarchive:
    src: /home/ubuntu/packages/pycharm-community-2017.2.4.tar.gz
    dest: /opt
    remote_src: true

- name: PyCharm - start
  command: /opt/pycharm-community-2017.2.4/bin/pycharm.sh
  become: true
  become_user: ubuntu
